### ISSUE TITLE
Many deprecation warnings

### ISSUE THREAD

**Issue by TimurDela** [sanic-org/tracerite#8]
Hello,

I guess tracerite gets installed by default by sanic.
In any case, it causes a chain of deprecation warnings in my code, the first one being

> tracerite/__init__.py:1: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    import pkg_resources

**Comment by Tronic** [comment]
I suppose a replacement for that module would be in order. Feel free to look at it if you have the time. I am occupied with other projects at this time but will have a look at some later time if no-one else makes a PR soon.

**Comment by TimurDela** [comment]
The readme does not include any information about setting up the development environment and I am not familiar with `setup.py`. All my attempts to use it seem to trigger further deprecation warnings and errors. Sorry :-(

**Comment by Tronic** [comment]
Fixed in git, needs release 1.1.1.

**Comment by KevinGDialpad** [comment]
https://github.com/sanic-org/tracerite/commit/4417b7018d61987293c1d4604654dfb4223489de didn't quite fix the problem, I think. I'm seeing the same warning coming from https://github.com/sanic-org/tracerite/blob/4417b7018d61987293c1d4604654dfb4223489de/tracerite/html.py#L1
